### ISSUE TITLE
Frequent exception while trying to publish data

### ISSUE THREAD

**Issue by jennolsen84** [tavendo/AutobahnPython#422] opened 2015-06-26 03:47 UTC
Hi,

When I try to publish a message, I get this exception after a few messages.  Here is the stack trace:

I am using python 3.4.2, asyncio, autobahn 0.10.4

The variable ```to_send``` is a dict that was formated using ```'{}'.format(d)``` and only contains simple strings and integers

```
  Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/srv/myutils/myutils/publisher.py", line 73, in _message_thread_proc
    self.on_message(item)
  File "/srv/myutils/myutils/publisher.py", line 183, in on_message
    r = self._session_factory._myAppSession.publish(topic, to_send)#, options=publish_options)
  File "/root/pyenvs/my_env/lib/python3.4/site-packages/autobahn/wamp/protocol.py", line 1026, in publish
    raise e
  File "/root/pyenvs/my_env/lib/python3.4/site-packages/autobahn/wamp/protocol.py", line 1022, in publish
    self._transport.send(msg)
  File "/root/pyenvs/my_env/lib/python3.4/site-packages/autobahn/wamp/websocket.py", line 122, in send
    self.sendMessage(payload, isBinary)
  File "/root/pyenvs/my_env/lib/python3.4/site-packages/autobahn/websocket/protocol.py", line 2436, in sendMessage
    self.sendMessageHybi(payload, isBinary, fragmentSize, sync, doNotCompress)
  File "/root/pyenvs/my_env/lib/python3.4/site-packages/autobahn/websocket/protocol.py", line 2500, in sendMessageHybi
    self.sendFrame(opcode=opcode, payload=payload, sync=sync, rsv=4 if sendCompressed else 0)
  File "/root/pyenvs/my_env/lib/python3.4/site-packages/autobahn/websocket/protocol.py", line 2072, in sendFrame
    self.sendData(raw, sync, chopsize)
  File "/root/pyenvs/my_env/lib/python3.4/site-packages/autobahn/websocket/protocol.py", line 1434, in sendData
    self.transport.write(data)
  File "/usr/lib/python3.4/asyncio/selector_events.py", line 898, in write
    self._buffer.extend(data)
BufferError: Existing exports of data: object cannot be re-sized

```

**Comment by oberstet** [comment] 2015-06-26 11:49
we can't reproduce this without a test program triggering this.

**Comment by jennolsen84** [comment] 2015-06-26 13:04
Unfortunately, I can only reproduce this in "prod"... communicating over ssl and crossbar running on a different host.  It works just fine in dev (though on 1 machine between 2 docker instances).

I can try putting the publisher and crossbar on different hosts in dev to see if I can reproduce it.

Do you think enabling wamp debugging or something like that would help in this case?

**Comment by oberstet** [comment] 2015-06-26 13:07
To be honest, I have doubts this is related to Autobahn or Crossbar.io at all ("BufferError: Existing exports of data: object cannot be re-sized"). Try changing the data. Ask on asyncio mailing list. I don't think enabling debug will reveal more. If you can't provide a reproducing example, please close it.

**Comment by oberstet** [comment] 2015-06-26 13:27
maybe this helps:

* http://stackoverflow.com/questions/20307726/example-to-throw-a-buffererror
* https://mail.python.org/pipermail/python-bugs-list/2014-June/242830.html

Also: `_message_thread_proc`. Are you using threads?

**Comment by jennolsen84** [comment] 2015-06-26 14:13
Yes, using threads.  I suspect it might be threading related too.  Not sure what your reference to ```_message_thread_proc``` was.  I think we'll be able to solve it, and I should be able to close this matter soon.  Unlikely this is a AutobahnPython issue at this point

We have a separate thread to push out messages.  We also usually push out messages with acknowledgements turned on, and do not wait to wait for them on the main thread.  Since we wanted to push out the message right away (and also not be "blocked" on the other work), we used a queue between the main thread and the thread that is responsible for all the WAMP communication.

**Comment by oberstet** [comment] 2015-06-26 14:17
Threads are likely the source of the problem. E.g. in Twisted, you must use deferToThread, callFromThread etc otherwise chaos will unfold.

Why are you using threads anyway? Generally, there are only 2 valid reasons: must call blocking code or must run CPU bound code.

Am 26.06.2015 4:13 nachm. schrieb jennolsen84 <notifications@github.com>:

Yes, using threads. I suspect it might be threading related too. Not sure what your reference to _message_thread_proc was. I think we'll be able to solve it, and I should be able to close this matter soon. Unlikely this is a AutobahnPython issue at this point

We have a separate thread to push out messages. We also usually push out messages with acknowledgements turned on, and do not wait to wait for them on the main thread. Since we wanted to push out the message right away (and also not be "blocked" on the other work), we used a queue between the main thread and the thread that is responsible for all the WAMP communication.

**Closed** 2015-06-26 19:07 UTC
