### ISSUE TITLE
Bad practice with assert in codebase

### ISSUE THREAD

**Issue by slav0nic** [tavendo/AutobahnPython#483] opened 2015-09-05 20:30 UTC
assert is fine for tests, but you can got some troubles in main codebase like this:

```bash
slav0nic@pc:/tmp$ cat ooops.py 
assert(1<0)
slav0nic@pc:/tmp$ python ooops.py 
Traceback (most recent call last):
  File "ooops.py", line 1, in <module>
    assert(1<0)
AssertionError
slav0nic@pc:/tmp$ python -O ooops.py 
slav0nic@pc:/tmp$ python -OO ooops.py 
slav0nic@pc:/tmp$ 
```
 afaik in Debian py modules compiled to pyc after installation, and your will got some troubles with asserts

https://github.com/tavendo/AutobahnPython/search?utf8=%E2%9C%93&q=assert+NOT+test
https://github.com/crossbario/crossbar/search?utf8=%E2%9C%93&q=assert+NOT+test&type=Code

**Comment by oberstet** [comment] 2015-09-06 08:08
duplicate of https://github.com/tavendo/AutobahnPython/issues/99

**Closed by oberstet** 2015-09-06 08:08 UTC

**Comment by oberstet** [comment] 2015-09-06 08:10
@slav0nic slightly unrelated rambling: I don't care much about distro Python packaging - it's simple: don't use it. There is no value in distro packaged Python packages.

**Comment by oberstet** [comment] 2015-09-16 16:47
@slav0nic pls see here .. we are gonna change it: https://github.com/tavendo/AutobahnPython/blob/master/DEVELOPERS.md#use-of-assert-vs-exceptions
